nameOverride: ""
fullnameOverride: ""

replicaCount: 10

image:
  repository: nginx
  tag: "1.27.4"
  pullPolicy: IfNotPresent

containerPort: 80

rollout:
  steps:
    - setWeight: 10
    - pause: {}
    - setWeight: 50
    - pause: {}
    - setWeight: 100

karmada:
  clusters:
    - name: member1
      weight: 1
    - name: member2
      weight: 1
  overrides:
    - clusterName: member1
      env:
        - name: ZONE
          value: member1
    - clusterName: member2
      env:
        - name: ZONE
          value: member2
