apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "argocon-demo.fullname" . }}
  labels:
    {{- include "argocon-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argocon-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argocon-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
  strategy:
    canary:
      stableService: {{ include "argocon-demo.fullname" . }}-stable
      canaryService: {{ include "argocon-demo.fullname" . }}-canary
      steps:
        {{- toYaml .Values.rollout.steps | nindent 8 }}
