apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocon-demo.fullname" . }}-stable
  labels:
    {{- include "argocon-demo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "argocon-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocon-demo.fullname" . }}-canary
  labels:
    {{- include "argocon-demo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "argocon-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
